name: Assign Me Action
author: TAKANOME-DEV
description: Enable a '/assign-me' command/comment that allows contributors to assign themselves issues.

runs:
  using: node20
  main: dist/index.js

branding:
  icon: activity
  color: white

inputs:
  github_token:
    default: ${{ github.token }}
    required: true
    description: The GitHub token used to authenticate API requests.
  self_assign_cmd:
    description: The command that assigns the issue to the one who triggered it
    default: /assign-me
  self_unassign_cmd:
    description: The command that unassigns the issue from the user who triggered it, if they are already assigned.
    default: /unassign-me
  assign_user_cmd:
    description: The command that assigns the user to the issue
    default: /assign
  unassign_user_cmd:
    description: The command that unassigns the user from the issue, if they are assigned.
    default: /unassign
  maintainers:
    description: >
      A list of maintainers authorized to use `/assign` and `/unassign` commands.
      List the usernames with comma separated. If not set, the usage of those commands will be ignored.
    default: '' # i.e: 'takanome-dev,octokit'
    required: true
  assigned_label:
    description: The label applied to issues when they are assigned by this action to track assignments.
    default: ðŸ“ Assigned
  required_label:
    description: If set, the issue must have this label in order for users to self-assign it.
    required: false
    default: ''
  days_until_unassign:
    description: The number of days after assignment before the user is automatically unassigned (if the issue remains open).
    default: '7'
  pin_label:
    default: ðŸ“Œ Pinned
    description: A label that prevents automatic unassignment, typically for long-term issues.
  assigned_comment:
    description: >
      The comment posted after a user has assigned themselves to an issue.
    default: |
      ðŸ‘‹ Hey @{{ handle }}, thanks for your interest in this issue! ðŸŽ‰

      > [!NOTE]
      > â³ Please note, you will be automatically unassigned if the issue isn't closed within **{{ total_days }} days** (by **{{ unassigned_date }}**).
      > A maintainer can also add the "**{{ pin_label }}**"" label to prevent automatic unassignment.
  already_assigned_comment:
    description: >
      The comment posted when a user tries to assign themselves to an issue that is already assigned.
    default: |
      ðŸ‘‹ Hey @{{ handle }}, this issue is already assigned to @{{ assignee }}.

      > [!NOTE]
      > â³ If the issue isn't closed by **{{ unassigned_date }}**, it will be automatically unassigned.
      > A maintainer can also add you to the list of assignees or swap you with the current assignee.
  unassigned_comment:
    description: >
      The comment posted after a user is unassigned from an issue.
    default: |
      ðŸ‘‹ Hey @{{ handle }}, you've been automatically unassigned from this issue due to inactivity.

      > [!NOTE]
      > If you'd like to be re-assigned, just leave another comment or ask a maintainer to assign you again.
      > If you're still actively working on the issue, let us know by commenting, and we can pin it to prevent automatic unassignment.
