name: Assign Me Action
author: TAKANOME-DEV
description: Enable a '/assign-me' command/comment that allows contributors to assign themselves issues.

runs:
  using: node16
  main: dist/index.js

branding:
  icon: activity
  color: white

inputs:
  github_token:
    default: ${{ github.token }}
    required: true
    description: The GitHub token used to authenticate API requests.
  self_assign_cmd:
    description: The command that assigns the issue to the one who triggered it
    default: /assign-me
  self_unassign_cmd:
    description: The command that unassigns the issue from the user who triggered it, if they are already assigned.
    default: /unassign-me
  assign_commenter_cmd:
    description: The command that assigns the commenter to the issue
    default: /assign-commenter
  unassign_commenter_cmd:
    description: The command that unassigns the commenter from the issue, if they are assigned.
    default: /unassign-commenter
  assigned_label:
    description: The label applied to issues when they are assigned by this action to track assignments.
    default: 📍 Assigned
  required_label:
    description: If set, the issue must have this label in order for users to self-assign it.
  days_until_unassign:
    description: The number of days after assignment before the user is automatically unassigned (if the issue remains open).
    default: 7
  pin_label:
    default: 📌 Pinned
    description: A label that prevents automatic unassignment, typically for long-term issues.
  assigned_comment:
    description: >
      The comment posted after a user has assigned themselves to an issue.
    default: |
      👋 Hey @{{ comment.user.login }}, thanks for your interest in this issue! 🎉

      ⚠ Note that this issue will become unassigned if it isn't closed within **{{ totalDays }} days**.

      🔧 A maintainer can also add the **{{ inputs.pin_label }}** label to prevent it from being unassigned automatically.
  already_assigned_comment:
    description: >
      The comment posted when a user tries to assign themselves to an issue that is already assigned.
    default: |
      👋 Hey @{{ comment.user.login }}, this issue is already assigned to @{{ assignee.login }}.

      ⚠️ It will become unassigned if it isn't closed within **{{ daysUntilUnassign }} days**. 

      🔧 A maintainer can also add you to the list of assignees or swap you with the current assignee.
  unassigned_comment:
     description: >
      The comment posted after a user is unassigned from an issue.
    default: |
      👋 Hey @{{ comment.user.login }}, you've been unassigned from this issue.

      🔧 If you'd like to get re-assigned, feel free to comment again or ask a maintainer to re-assign you.

      📝 Remember, if you are actively working on the issue, let us know by commenting and we can pin it for you.
