name: 🚀 Feature request
description: Suggest an idea for this project 💡
title: 'Feature: <a short description of the feature request>'
labels: [👀 needs triage, 💡 feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: dropdown
    attributes:
      multiple: false
      label: Type of feature
      description: Select the type of feature request, the lowercase should also be the PR prefix.
      options:
        - '💡 Feature'
        - '🐛 Fix'
        - '📝 Documentation'
        - '🎨 Style'
        - '🧑‍💻 Refactor'
        - '🔥 Performance'
        - '✅ Test'
        - '🤖 Build'
        - '🔁 CI'
        - '📦 Chore'
        - '⏩ Revert'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution
      description: Describe the solution you'd like.
  - type: input
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem or helpful links here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/takanome-dev/assign-issue-action/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Contributing Docs
      description: If you plan on contributing code please read - [Contribution Guide](https://github.com/takanome-dev/assign-issue-action/blob/master/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Contribution Docs
          required: false
